# Generated by Django 4.1.7 on 2023-03-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpa",
            name="aid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.address",
                verbose_name="AID",
            ),
        ),
        migrations.AlterField(
            model_name="cpa",
            name="co_sales",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Co_Sales ID"
            ),
        ),
        migrations.AlterField(
            model_name="cpa",
            name="pid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app01.piano",
                verbose_name="PID",
            ),
        ),
    ]
