# Generated by Django 4.1.7 on 2023-04-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_user_alter_cpa_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=128, null=True, verbose_name="email"
            ),
        ),
    ]
