# Generated by Django 4.0.10 on 2023-04-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=32, unique=True, verbose_name='Phone Number'),
        ),
    ]
