# Generated by Django 4.0.10 on 2023-04-24 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0XXXXXXXXX'. Up to 10 digits allowed.", regex='^0\\d{9}')], verbose_name='Phone Number'),
        ),
    ]
