# Generated by Django 4.0.3 on 2023-04-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('suburb', models.CharField(max_length=255)),
                ('postcode', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(blank=True, null=True)),
                ('aid', models.IntegerField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('sn', models.CharField(blank=True, max_length=255, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
                ('co_sales', models.IntegerField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('active', models.CharField(blank=True, max_length=255, null=True)),
                ('directly_sold', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cpa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('submodel', models.CharField(blank=True, max_length=255, null=True)),
                ('colour', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tuning',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('mid', models.IntegerField()),
                ('tuning_date', models.DateField(blank=True, null=True)),
                ('piano_condition', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tuning',
                'managed': False,
            },
        ),
    ]
