# Generated by Django 4.1.7 on 2023-02-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo", old_name="salary", new_name="account",
        ),
    ]
