# Generated by Django 4.1.7 on 2023-02-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_alter_userinfo_account_alter_userinfo_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrettyNum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=32, verbose_name="Phone No.")),
                ("price", models.IntegerField(default=0, verbose_name="Price")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                            (4, "Level 4"),
                        ],
                        default=1,
                        verbose_name="Level",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Sold"), (2, "Available")], verbose_name="Status"
                    ),
                ),
            ],
        ),
    ]
