# Generated by Django 4.1.7 on 2023-03-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_prettynum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="User Name")),
                ("password", models.CharField(max_length=64, verbose_name="Password")),
            ],
        ),
    ]
