# Generated by Django 4.1.7 on 2023-03-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "Emergency"), (2, "Important"), (3, "Temporary")],
                        default=1,
                        verbose_name="Level",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="Title")),
                ("detail", models.TextField(verbose_name="Detail")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.admin",
                        verbose_name="Leader",
                    ),
                ),
            ],
        ),
    ]
