# Generated by Django 4.1.7 on 2023-03-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0006_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.CharField(max_length=64, verbose_name="Order No.")),
                ("title", models.CharField(max_length=32, verbose_name="Product Name")),
                ("price", models.IntegerField(verbose_name="Price")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Paid"), (2, "Unpaid")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.admin",
                        verbose_name="Admin",
                    ),
                ),
            ],
        ),
    ]
