# Generated by Django 4.1.7 on 2023-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                ("age", models.IntegerField(verbose_name="Age")),
                ("img", models.CharField(max_length=128, verbose_name="Head")),
            ],
        ),
    ]
