# Generated by Django 4.1.7 on 2023-03-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0008_boss"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="City Name")),
                ("count", models.IntegerField(verbose_name="Population")),
                (
                    "logo",
                    models.FileField(
                        max_length=128, upload_to="city/", verbose_name="Logo"
                    ),
                ),
            ],
        ),
    ]
