# Generated by Django 4.1.7 on 2023-03-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0010_address_address1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=256, verbose_name="Address")),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Unit or Apartment No.",
                    ),
                ),
                ("suburb", models.CharField(max_length=64, verbose_name="Suburb")),
                ("postcode", models.CharField(max_length=8, verbose_name="Postcode")),
                ("lat", models.DecimalField(decimal_places=8, max_digits=11)),
                ("long", models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
    ]
