version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - cache:/data
  cachingapi:
    build:
      context: ../WAREHOUSE/
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8000'
    depends_on:
      - cache
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    volumes:
      - ../tmp_data/DATA:/code/DATA
      - ../tmp_data/geojson:/code/geojson
volumes:
  cache:
    driver: local