version: "3.9"

services:
  
  web: 
    build:
      context: ../APP
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    ports: 
      - '8000:8000'
    depends_on:
      - mysql
    restart: no
    environment:
      - WAIT_HOSTS=mysql:3306
      - MYSQL_HOST=mysql
      - ENVIRONMENT=docker
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_PORT=${MYSQL_PORT}

      - DJANGO_SECRET_KEY=secretkey
      - SQL_USER=${MYSQL_USER}
      - SQL_PASSWORD=password
      - SQL_NAME=db
      - SQL_HOST=localhost
      - SQL_PORT=3306

      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

      # FOR S3 BUCKET
      - ACCESS_KEY="sdgsdh"
      - ACCESS_SECRET="dfff"
      - BUCKET_NAME="yongbin"

    volumes: 
      - type: bind
        source: ../APP
        target: /app

      
  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      # Database name
      MYSQL_DATABASE: ${MYSQL_DB}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      CHARSET: utf8
    restart: always
    ports:
      - '3306:3306'
  
  myphpadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 5050:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always

volumes:
  mysql-data:
